app/main/forms.py
from datetime import datetime
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, HiddenField, TextAreaField, SelectField, DateTimeField
from wtforms.validators import ValidationError, DataRequired, Length
from flask_babel import _, lazy_gettext as _l
from app.models import User


class EditProfileForm(FlaskForm):
    username = StringField(_l('Username'), validators=[DataRequired()])
    about_me = TextAreaField(_l('About me'),
                             validators=[Length(min=0, max=140)])
    submit = SubmitField(_l('Submit'))

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError(_('Please use a different username.'))


class PostForm(FlaskForm):
    post = TextAreaField(_l('Say something'), validators=[DataRequired()])
    submit = SubmitField(_l('Submit'))


CHOICES = [('1', '吹水台'), ('2', '高登熱'), ('3', '硬件台'), ('4', '手機台'), ('5', '音樂台'), ('6', '飲食台'),
           ('7', '上班台'), ('8', '寵物台'), ('9', '買賣台'), ('10', '活動台')]


class TopicForm(FlaskForm):
    pid = HiddenField()
    tag = SelectField('tag', choices=CHOICES)
    topic = StringField(_l('Topic'), validators=[DataRequired(Length(1, 64))])
    post = TextAreaField(_l('Content'), validators=[Length(min=0, max=140)])
    timestamp = HiddenField("Timestamp", default=datetime.utcnow, validators=[DataRequired()])
    user_id = HiddenField()
    user_name = HiddenField()
    submit = SubmitField(_l('Submit'))


class ReplyForm(FlaskForm):
    id = HiddenField()
    post = TextAreaField(_l('Content'), validators=[Length(min=0, max=140)])
    timestamp = HiddenField("Timestamp", default=datetime.utcnow, validators=[DataRequired()])
    user_id = HiddenField()
    name = HiddenField()
    submit = SubmitField(_l('Submit'))

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, g
from flask_login import current_user, login_required
from flask_babel import _, get_locale
from app import current_app, db
from app.main.forms import EditProfileForm, PostForm, TopicForm, ReplyForm
from app.models import User, Post, Newtopic, Reply, Record
from app.main import bp


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
    g.locale = str(get_locale())


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/main', methods=['GET', 'POST'])
def main():
    return render_template('main.html', Newtopic=Newtopic.query.filter_by(tag=1).all())


@bp.route('/activity_post', methods=['GET'])
def activity_post():
    return render_template('activity_post.html', Newtopic=Newtopic.query.filter_by(tag=10).all())


@bp.route('/sell_post', methods=['GET'])
def sell_post():
    return render_template('sell_post.html', Newtopic=Newtopic.query.filter_by(tag=9).all())


@bp.route('/pet_post', methods=['GET'])
def pet_post():
    return render_template('pet_post.html', Newtopic=Newtopic.query.filter_by(tag=8).all())


@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(body=form.post.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash(_('Your post is now live!'))
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)
    posts = current_user.followed_posts().paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.index', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.index', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('index.html', title=_('Home'), form=form,
                           posts=posts.items, next_url=next_url,
                           prev_url=prev_url)


@bp.route('/explore')
@login_required
def explore():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.explore', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.explore', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('index.html', title=_('Explore'),
                           posts=posts.items, next_url=next_url,
                           prev_url=prev_url)


@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.user', username=user.username, page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.user', username=user.username, page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('user.html', user=user, posts=posts.items,
                           next_url=next_url, prev_url=prev_url)


@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash(_('Your changes have been saved.'))
        return redirect(url_for('main.edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', title=_('Edit Profile'),
                           form=form)


@bp.route('/new_topic/<username>', methods=['GET', 'POST'])
@login_required
def new_topic(username):
    user = User.query.filter_by(username=username).first()
    form = TopicForm()
    if form.validate_on_submit():
        record = Newtopic(topic=form.topic.data, tag=form.tag.data, post=form.post.data, user_id=user.id)
        db.session.add(record)
        db.session.commit()
        flash(_('Your post is now live!'))
        return redirect(url_for('main.main'))
    return render_template('new_topic.html', title=_('new_topic'), form=form)


@bp.route('/follow/<username>')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(_('User %(username)s not found.', username=username))
        return redirect(url_for('main.index'))
    if user == current_user:
        flash(_('You cannot follow yourself!'))
        return redirect(url_for('main.user', username=username))
    current_user.follow(user)
    db.session.commit()
    flash(_('You are following %(username)s!', username=username))
    return redirect(url_for('main.user', username=username))


@bp.route('/unfollow/<username>')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(_('User %(username)s not found.', username=username))
        return redirect(url_for('main.index'))
    if user == current_user:
        flash(_('You cannot unfollow yourself!'))
        return redirect(url_for('main.user', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash(_('You are not following %(username)s.', username=username))
    return redirect(url_for('main.user', username=username))


@bp.route('/block/<username>')
@login_required
def block(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(_('User %(username)s not found.', username=username))
        return redirect(url_for('main.index'))
    if user == current_user:
        flash(_('You cannot block yourself!'))
        return redirect(url_for('main.user', username=username))
    current_user.block(user)
    db.session.commit()
    flash(_('You blocked %(username)s!', username=username))
    return redirect(url_for('main.user', username=username))


@bp.route('/unblock/<username>')
@login_required
def unblock(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(_('User %(username)s not found.', username=username))
        return redirect(url_for('main.main'))
    if user == current_user:
        flash(_('You cannot block yourself!'))
        return redirect(url_for('main.user', username=username))
    current_user.unblock(user)
    db.session.commit()
    flash(_('You unblocked %(username)s.', username=username))
    return redirect(url_for('main.user', username=username))

app/templates/activity_post.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block current_app_content %}
    <div class="col-sm-4 col-md-6">
        <div class="container" style="width: 700px">
            <div class="tab-content" style="margin-top: 50px">
                <ul class="nav nav-tabs list-inline" style="width: 700px">
                    <li>
                        <button type="button" class="btn btn-circle btn-sm"
                                style="font-size: 18px; margin-top: -3px;"><a href="{{ url_for('main.sell_post') }}">
                            <span class="glyphicon glyphicon-refresh" style="top: 3px"></span></a>
                        </button>
                    </li>
                    <li><h4>活動台</h4></li>
                    <li class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            <span class='far fa-comment-dots fa-1x' style="margin-right: 9px"></span>最後回應時間<span
                                class="caret" style="margin-left: 12px"></span></button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <li><a href="#"><span class='far fa-comment-dots fa-1x' style="margin-right: 9px"></span>最後回應時間</a>
                            </li>
                            <li><a href="#"><span class='far fa-comment-dots fa-1x'
                                                  style="margin-right: 9px"></span>發表時間</a>
                            </li>
                            <li><a href="#"><span class='fas fa-fire fa-1x' style="margin-right: 9px"></span>熱門</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">全部<span class="caret"
                                                                                   style="margin-left: 12px"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="#">全部</a></li>
                            <li><a href="#">正式</a></li>
                            <li><a href="#">公海</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="row">
                {% for NewTopics in Newtopic %}
                    <div class="list-group" style="margin-top: 25px">
                        <a href="#" class="list-group-item list-group-item-action active" aria-current="true" style="color: black;
                            background-color: white; border-color: black;">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1" style="font-size: 20px; color: #f44986">{{ NewTopics.topic }}</h5>
                            </div>
                            <small>{{ moment(NewTopics.timestamp).fromNow() }}</small>
                            <p class="mb-1">{{ NewTopics.post }}</p>
                        </a>
                    </div>
                {% endfor %}
                {% for data in data_set %}
                    <a href="{{ data.url }}"><img src="{{ data.image }}"></a>
                {% endfor %}
                </div>
            </div>
            <div class="col-sm-1 col-md-2 sidenav">
                <div class="well">
                    <p>ADS</p>
                </div>
                <div class="well">
                    <p>ADS</p>
                </div>
            </div>
        </div>

{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - Microblog{% else %}{{ _('Welcome to Microblog') }}{% endif %}
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    {{ super() }}
    <style>
        .btn-circle {
            margin: 5px 5px 5px 5px;
            width: 40px;
            height: 40px;
            padding: 6px 0px;
            border-radius: 20px;
            text-align: center;
        "
        }

        collapsing {
            width: 0;
            transition-property: width;
            height: 100%;
            white-space: nowrap;
        }

        . hide {
            display: none;
        }

        .myDIV:hover + . hide {
            display: block;
            color: red;
        }

        navbarToggleExternalContent {
            transform: translateX(-100%);
            transition: transform .35s ease;
            display: block;
            height: 100%;
            min-height: 100%;
        }

        #navbarToggleExternalContent h6 {
            display: block;
            color: black;
            text-align: left;
            padding: 5px 8px;
            text-decoration: none;
            font-size: 13px;

        }

        #navbarToggleExternalContent li {
            display: block;
            color: black;
            text-align: center;
            padding: 5px 8px;
            text-decoration: none;
            font-size: 13px;
            border-bottom: 3px solid transparent;
        }

        . navbarToggleExternalContent. menu-show {
            transform: translateX(0%);
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        row. content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        . sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            . sidenav {
                height: auto;
                padding: 15px;
            }

            row. content {
                height: auto;
            }
        }

        . card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            padding: 16px;
            text-align: center;
            background-color: #f1f1f1;
        }
    </style>

    <div class="container"></div>
    <nav class="navbar navbar-default " role="navigation" style="background-color: #346599;">
        <div class="container-fluid">
            <div class="navbar-header">
                <button class="navbar-brand" type="button" data-toggle="collapse"
                        data-target="#navbarToggleExternalContent" style="margin-left: 165px">
                    <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <div id="listtop" class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('main.main') }}"><span class="glyphicon glyphicon-home"></span></a>
                    </li>
                    <li>
                                <!--<h1> {{ current_user }}</h1>-->
                        <a href="{{ url_for('main.new_topic',  username=current_user.username) }}">NewPost</a>
                    </li>
                    <li>
                        <a href="{{ url_for('auth.login') }}"><span class="glyphicon glyphicon-envelope"></span></a>
                    </li>

                    <li>
                        {% if current_user.is_anonymous %}
                        <li><a href="{{ url_for('auth.login') }}"><span class="glyphicon glyphicon-user"></span>{{ _('Login') }}</a></li>
                    {% else %}
                        <li><a href="{{ url_for('main.user', username=current_user.username) }}"><span class="glyphicon glyphicon-user"></span>{{ _('Profile') }}</a>
                        </li>
                        <li><a href="{{ url_for('auth.logout') }}"><span class="glyphicon glyphicon-user"></span>{{ _('Logout') }}</a></li>
                    {% endif %}
                    </li>
                </div>
                <div class="dropdown">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false"
                            style="padding-right: 20px; float: none; margin-top: 8px; border-radius: 4px 0px 0px 4px; margin-left: 191px;">
                        貼文<span class="caret" style="margin-left: 12px"></span></button>
                    <ul class="dropdown-menu" style="margin-left: 392px; min-width: 83px;">
                        <li><a href="#">貼文</a></li>
                        <li><a href="#">作者</a></li>
                    </ul>
                </div>
                <form class="navbar-form navbar-centered" action="#" method="GET"
                      style="float: none; position: absolute; top: 34%; left: 50%; transform: translate(-50%, -50%)">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search..." id="query" name="search"
                               value="">
                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-success"><span
                                    class="glyphicon glyphicon-search"></span></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-info" role="alert">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {# current_application content needs to be provided in the current_app_content block #}

        {% include 'leftnav.html' %}
        {% block current_app_content %}{% endblock %}

    </div>
{% endblock %}

{% block scripts %}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.lang(g.locale) }}
    <script>

        const $menu = $('#navbarToggleExternalContent');

        $menu.on('show.bs.collapse', function () {
            $menu.addClass('menu-show');
        });

        $menu.on('hide.bs.collapse', function () {
            $menu.removeClass('menu-show');
        });


    </script>
{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block current_app_content %}
    <h1>{{ _('Edit Profile') }}</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/leftnav.html
<div class="container-fluid text-center" style="float:left; margin-left: -60px">
        <div class="row content">
            <div class="col-sm-2 col-md-3 sidenav" style="width: 200px">
                <div class="bg-dark collapse position-fixed" id="navbarToggleExternalContent">
                    <ul class="nav py-4">
                        <h6>個人</h6>
                        <div class="first_item">
                            <li><a href="#chatting"><span class="glyphicon glyphicon-tint" aria-hidden="true"
                                                          style="float: left"></span>回帶</a>
                            </li>
                        </div>
                        <div class="first_item_2">
                            <li><a href="#study"><span class="fas fa-fire" aria-hidden="true"
                                                       style="float: left"></span>留名</a></li>
                        </div>
                    </ul>
                    <ul class="nav py-4">
                        <h6>推薦 </h6>
                        <div class="Second_item">
                            <li><a href="#chatting"><span class="glyphicon glyphicon-tint" aria-hidden="true"
                                                          style="float: left"></span>吹水台</a>
                            </li>
                        </div>
                        <div class="Second_item_2">
                            <li><a href="#study"><span class="fas fa-fire" aria-hidden="true"
                                                       style="float: left"></span>高登熱</a>
                            </li>
                        </div>
                    </ul>
                    <ul class="nav py-4">
                        <h6>數碼 </h6>
                        <div class="Third_item">
                            <li><a href="#chatting"><span class="bi bi-cpu" aria-hidden="true"
                                                          style="float: left"></span>硬件台</a>
                            </li>
                        </div>
                        <div class="Third_item_2">
                            <li><a href="#study"><span class="fas fa-mobile-alt" aria-hidden="true"
                                                       style="float: left"></span>手機台</a>
                            </li>
                        </div>
                    </ul>
                    <ul class="nav py-4">
                        <h6>消閒 </h6>
                        <div class="Third_item">
                            <li><a href="#chatting"><span class="glyphicon glyphicon-tint" aria-hidden="true"
                                                          style="float: left"></span>音樂台</a>
                            </li>
                        </div>
                        <div class="Third_item_2">
                            <li><a href="#study"><span class="glyphicon glyphicon-phone" aria-hidden="true"
                                                       style="float: left"></span>飲食台</a>
                            </li>
                        </div>
                    </ul>
                    <h6>生活 </h6>
                    <div class="Third_item">
                        <li><a href="#chatting"><span class="glyphicon glyphicon-tint" aria-hidden="true"
                                                      style="float: left"></span>上班台</a>
                        </li>
                    </div>
                    <div class="Third_item_2">
                        <li>
                            <a href="{{ url_for('main.pet_post') }}"><span class="glyphicon glyphicon-phone" aria-hidden="true"
                                                   style="float: left"></span>寵物台</a>
                        </li>
                    </div>
                    </ul>
                    <h6>其他 </h6>
                    <div class="Third_item">
                        <!--<h1> {{ current_user }}</h1>-->
                        <li><a href="{{ url_for('main.sell_post') }}"><span class="glyphicon glyphicon-tint" aria-hidden="true"
                                                      style="float: left"></span>買賣台</a>
                        </li>
                    </div>
                    <div class="Third_item_2">
                        <!--<h1> {{ current_user }}</h1>-->
                        <li><a href="{{ url_for('main.activity_post') }}"><span class="glyphicon glyphicon-phone" aria-hidden="true"
                                                   style="float: left"></span>活動台</a>
                        </li>
                    </div>
                    </ul>
                </div>
            </div>
        </div>
</div>

app/templates/pet_post.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block current_app_content %}
    <div class="col-sm-4 col-md-6">
        <div class="container" style="width: 700px">
            <div class="tab-content" style="margin-top: 50px">
                <ul class="nav nav-tabs list-inline" style="width: 700px">
                    <li>
                        <button type="button" class="btn btn-circle btn-sm"
                                style="font-size: 18px; margin-top: -3px;"><a href="{{ url_for('main.sell_post') }}">
                            <span class="glyphicon glyphicon-refresh" style="top: 3px"></span></a>
                        </button>
                    </li>
                    <li><h4>寵物台</h4></li>
                    <li class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            <span class='far fa-comment-dots fa-1x' style="margin-right: 9px"></span>最後回應時間<span
                                class="caret" style="margin-left: 12px"></span></button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <li><a href="#"><span class='far fa-comment-dots fa-1x' style="margin-right: 9px"></span>最後回應時間</a>
                            </li>
                            <li><a href="#"><span class='far fa-comment-dots fa-1x'
                                                  style="margin-right: 9px"></span>發表時間</a>
                            </li>
                            <li><a href="#"><span class='fas fa-fire fa-1x' style="margin-right: 9px"></span>熱門</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">全部<span class="caret"
                                                                                   style="margin-left: 12px"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="#">全部</a></li>
                            <li><a href="#">正式</a></li>
                            <li><a href="#">公海</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="row">
                {% for NewTopics in Newtopic %}
                    <div class="list-group" style="margin-top: 25px">
                        <a href="#" class="list-group-item list-group-item-action active" aria-current="true" style="color: black;
                            background-color: white; border-color: black;">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1" style="font-size: 20px; color: #f44986">{{ NewTopics.topic }}</h5>
                            </div>
                            <small>{{ moment(NewTopics.timestamp).fromNow() }}</small>
                            <p class="mb-1">{{ NewTopics.post }}</p>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-sm-1 col-md-2 sidenav">
            <div class="well">
                <p>ADS</p>
            </div>
            <div class="well">
                <p>ADS</p>
            </div>
        </div>
    </div>

{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block current_app_content %}
    <table class="table table-hover">
        <tr>
            <td width="256px"><img src="{{ user.avatar(256) }}"></td>
            <td>
                <h1>{{ _('User') }}: {{ user.username }}</h1>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}
                    <p>{{ _('Last seen on') }}: {{ moment(user.last_seen).format('LLL') }}</p>
                {% endif %}
                <p>{{ _('%(count)d followers', count=user.followers.count()) }}, {{ _('%(count)d following', count=user.followed.count()) }}</p>
            <p>{{ _('%(count)d blockers', count=user.blockers.count()) }}</p>

                {% if user == current_user %}
                    <p><a href="{{ url_for('main.edit_profile') }}">{{ _('Edit your profile') }}</a></p>
                    <p><a href="{{ url_for('auth.reset_password_request') }}">{{ _('Reset Password') }}</a></p>
                {% elif not current_user.is_following(user) %}
                    <p><a href="{{ url_for('main.follow', username=user.username) }}">{{ _('Follow') }}</a></p>
                {% else %}
                    <p><a href="{{ url_for('main.unfollow', username=user.username) }}">{{ _('Unfollow') }}</a></p>
                {% endif %}
                {% if not current_user.is_blocked(user) %}
                    <p><a href="{{ url_for('main.block', username=user.username) }}">{{ _('Block') }}</a></p>
                {% elif current_user.is_blocked(user) %}
                    <p><a href="{{ url_for('main.unblock', username=user.username) }}">{{ _('Unblock') }}</a></p>
                {% endif %}
            </td>
        </tr>
    </table>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ _('Newer posts') }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ _('Older posts') }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}